"""empty message

Revision ID: 1f230cea0c49
Revises: ff6443ffc522
Create Date: 2021-02-21 17:15:47.962498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f230cea0c49'
down_revision = 'ff6443ffc522'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('total_shares', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'total_shares')
    # ### end Alembic commands ###
