"""empty message

Revision ID: d5d3ae20d385
Revises: 
Create Date: 2021-01-11 17:29:37.414042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5d3ae20d385'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('image_file', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('security_name', sa.String(length=20), nullable=False),
    sa.Column('security_details', sa.String(length=100), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_per_share', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fees', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('forex_rate', sa.Numeric(precision=4), nullable=True),
    sa.Column('acb', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('acb_change', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('amount_in_cad', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('amount_recieved', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('amount_recieved_details', sa.String(length=100), nullable=True),
    sa.Column('gain_loss', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('user')
    # ### end Alembic commands ###
